# Generated by Django 4.0.1 on 2022-01-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_votefact_created_at_alter_votefact_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='open',
            field=models.BooleanField(default=1),
        ),
    ]
